// <auto-generated />
using System;
using BetwayDiskiFantasy.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetwayDiskiFantasy.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812081731_AddUserAndSquadModels")]
    partial class AddUserAndSquadModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.SquadPlayer", b =>
                {
                    b.Property<int>("UserSquadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenchOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViceCaptain")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserSquadId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SquadPlayers");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.UserSquad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSquads");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.Player", b =>
                {
                    b.HasOne("BetwayDiskiFantasy.Api.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.SquadPlayer", b =>
                {
                    b.HasOne("BetwayDiskiFantasy.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetwayDiskiFantasy.Api.Models.UserSquad", "UserSquad")
                        .WithMany("SquadPlayers")
                        .HasForeignKey("UserSquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("UserSquad");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.UserSquad", b =>
                {
                    b.HasOne("BetwayDiskiFantasy.Api.Models.User", "User")
                        .WithOne("Squad")
                        .HasForeignKey("BetwayDiskiFantasy.Api.Models.UserSquad", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.User", b =>
                {
                    b.Navigation("Squad");
                });

            modelBuilder.Entity("BetwayDiskiFantasy.Api.Models.UserSquad", b =>
                {
                    b.Navigation("SquadPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
